### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [okjm3324/myapp#73]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
音声の再生(AB区間)できるのも確認しました。LGTMです。

## 静的コードチェックが入っている
・Rubocopを通しましょう。アクションで何も書かれていないものは1行にするようにとか指摘が出るかと思われます。
・使用していないファイルは削除しておきましょう。（viewファイルでそれらしきものが散見されました）
・viewファイルのインデントが半角4つになっているものがありました。半角2つに修正しましょう。(_header.html.erb)
・tracks/edit.html.erbの<script>タグの記載はRailsのJavaScript管理に移行しましょう（他も同様）。
・ルーティングもresourcesベースに寄せられないか検討して修正しましょう。（get 'search_artist' etc）
・余計なファイル、コード、コメントは削除しておきましょう。（コピーファイル？、2023-06-17-15-40-37.png、等々）

## 就活において十分な技術力を示せる機能を実装しているか
・結論から申しますと、十分な技術力を示せる水準には達していないと思いました。
・以下の機能の中から1つ以上実装できないか検討及び実装しましょう。

```
◯マルチ検索・オートコンプリート
概要：食べログの検索フォームのような、様々なカラムから検索可能な検索フォームです。1文字入力するたびに、候補が表示されるため、ユーザーの入力手間を減らし、入力ミスを減らすことができます。
使用技術・ライブラリ：
- Stimulus Autocomplete（Rails7 ）
  - https://github.com/afcapel/stimulus-autocomplete
- JQuery
  - https://github.com/xpeppers/rails-autocomplete

◯LINE通知（練習時間になったら通知してくれるetc）
概要：Webプッシュはまだ普及しておらず、アプリのプッシュ通知を利用したい方には、LINEプッシュ通知がおすすめです。簡単な連携で、自分の好きなタイミングにLINEを通じてプッシュ通知を行うことができます。
使用技術・ライブラリ：
- LINE Messaging API
  - LINE Messaging API SDK for Ruby
  - https://github.com/line/line-bot-sdk-ruby

◯レコメンド
概要：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
使用技術・ライブラリ：
- Amazon Personalize
  - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
  - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
- GCP Recommendations AI
  - https://cloud.google.com/recommendations?hl=ja
  - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
- アルゴリズム
  - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

◯チャット
概要：FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
使用技術・ライブラリ：
- WebSocket
  - https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）
  - https://railsguides.jp/action_cable_overview.html
```

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・独自ドメイン対応しましょう。
・最初に表示されるページ「アプリタイトル・説明です説明です...」は良くわからないので整備しましょう。
・ログインできる時とできない時が確認できました。一度調査しておくと良いかと思います。
・ヘッダーがボタンに重なってしまっていたりと、操作する中で面倒くささを感じる箇所が散見されたため修正しましょう。
・使い方が分からないため、どういったサービスで、どういったことができ、どういう操作を行うことでサービスを享受できるのかが分かるようにページを用意したり、画面上でそれが分かるようにしましょう。
・実装前なのか分かりませんが、ログイン後のページの「いいね」をクリックしても画面に変更が見られないので対応しましょう。
・アーティスト検索も左側に一列に表示される及び画像を押しても遷移しない、重複した文字列が表示されるが片方はリンク、もう片方はただの文字列になっていたりと使いにくかったので修正しましょう。
・曲選択部分も背景・文字が見にくく、ヘッダーにオーバーしているところも確認できたので、細かいですが修正しましょう。
・新規トラックの作成においてはボタンがヘッダーと重なってしまい、操作しづらかったです。
・左側のアプリケーション名の文字列をクリックしても、どこにも遷移できないのは不便に感じました。期待としてはトップもしくはマイページに遷移するものかと思いましたが、戻るにはブラウザバックするしか導線が無い点も不便に感じました。
・タイムラインも同様に縦一列というのが違和感を感じました。右側の何も無い空間があるのが気になりました。
・AB間再生できるページの何も無い背景ブルー系の枠が何のためにあるのかが分からず困惑しました。
・編集をクリックしても編集画面に遷移できず、都度新しく投稿を行わないといけない動線になっていそうなので修正しましょう。
・全体的にボタン・文字列etcの配置をPCでもスマホでも適切な位置・距離感にあるようにしましょう。

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by okjm3324** [comment]
レビューありがとうございます。
レビューいただいた内容をもとにissueを追加しました。
本リリースは11月7日の予定です。
よろしくお願いいたします。
